// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkMRL-b4hwvbZXiI8xcQVPv-nu2zU9NU',
    appId: '1:820807250549:web:da5a88956803a437907e3c',
    messagingSenderId: '820807250549',
    projectId: 'tasarimcalismasi2-c3dd8',
    authDomain: 'tasarimcalismasi2-c3dd8.firebaseapp.com',
    storageBucket: 'tasarimcalismasi2-c3dd8.firebasestorage.app',
    measurementId: 'G-TKEVJC32BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj94cVkbbqAFIU5mz609hyOKagL5nBmFg',
    appId: '1:820807250549:android:8067c0d80130e8e9907e3c',
    messagingSenderId: '820807250549',
    projectId: 'tasarimcalismasi2-c3dd8',
    storageBucket: 'tasarimcalismasi2-c3dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQv39PKxtPJzyX_wKgV2NRs0C_1HuUmI',
    appId: '1:820807250549:ios:9490b8d18737656b907e3c',
    messagingSenderId: '820807250549',
    projectId: 'tasarimcalismasi2-c3dd8',
    storageBucket: 'tasarimcalismasi2-c3dd8.firebasestorage.app',
    iosBundleId: 'com.example.tasarimCalismasi',
  );
}
